# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClashRoyale_app', '0004_auto_20170822_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('clan', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=0)),
                ('highest_trophies', models.IntegerField(default=0)),
                ('last_known_trophies', models.IntegerField(default=0)),
                ('challenge_cards_won', models.IntegerField(default=0)),
                ('tourney_cards_won', models.IntegerField(default=0)),
                ('total_donations', models.IntegerField(default=0)),
                ('prev_season_rank', models.IntegerField(default=0)),
                ('prev_season_trophies', models.IntegerField(default=0)),
                ('prev_season_highest', models.IntegerField(default=0)),
                ('best_season_rank', models.IntegerField(default=0)),
                ('previous_season_rank', models.IntegerField(default=0)),
                ('legendary_trophies', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
