# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClashRoyale_app', '0005_auto_20170822_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('uid', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('league', models.CharField(max_length=264)),
                ('score', models.IntegerField(default=0)),
                ('donations', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=20)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('clan', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=0)),
                ('highest_trophies', models.IntegerField(default=0)),
                ('last_known_trophies', models.IntegerField(default=0)),
                ('challenge_cards_won', models.IntegerField(default=0)),
                ('tourney_cards_won', models.IntegerField(default=0)),
                ('total_donations', models.IntegerField(default=0)),
                ('prev_season_rank', models.IntegerField(default=0)),
                ('prev_season_trophies', models.IntegerField(default=0)),
                ('prev_season_highest', models.IntegerField(default=0)),
                ('best_season_rank', models.IntegerField(default=0)),
                ('previous_season_rank', models.IntegerField(default=0)),
                ('legendary_trophies', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
